runtime: nodejs24
beta_settings:
  cloud_sql_instances: "cloudrc-492117:europe-central2:cloudrc"
env_variables:
  DB_USER: "postgres"
  DB_PASSWORD: "`~RJj@:B73x>2$Qj"
  DB_NAME: "cloudrc"
  INSTANCE_CONNECTION_NAME: "cloudrc-492117:europe-central2:cloudrc"
  DATABASE_URL: "postgresql://postgres:`~RJj@:B73x>2$Qj@/cloudrc?host=/cloudsql/cloudrc-492117:europe-central2:cloudrc"
  CORS_ORIGINS: "https://cloudrc-492117.web.app,http://localhost:5173,http://localhost:3000"
  AUTH_COOKIE_SAME_SITE: "none"